# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yast_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1315, 851)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 70, 1321, 20))
        self.line.setMinimumSize(QtCore.QSize(751, 0))
        self.line.setMaximumSize(QtCore.QSize(16777215, 20))
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(210, 80, 20, 631))
        self.line_2.setMinimumSize(QtCore.QSize(20, 0))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 631))
        self.line_2.setLineWidth(1)
        self.line_2.setMidLineWidth(5)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(-60, 700, 1381, 20))
        self.line_3.setMinimumSize(QtCore.QSize(781, 0))
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(1100, 720, 156, 23))
        self.buttonBox.setMinimumSize(QtCore.QSize(156, 0))
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 23))
        self.buttonBox.setStandardButtons(
            QtGui.QDialogButtonBox.Close | QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(230, 90, 1041, 611))
        self.groupBox.setMinimumSize(QtCore.QSize(501, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 611))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.scrollArea = QtGui.QScrollArea(self.groupBox)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 1021, 581))
        self.scrollArea.setMinimumSize(QtCore.QSize(481, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 581))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(
            QtCore.QRect(0, 0, 1019, 579))
        self.scrollAreaWidgetContents.setObjectName(
            _fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 1261, 61))
        self.groupBox_2.setMinimumSize(QtCore.QSize(721, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(110, 30, 1131, 20))
        self.lineEdit.setMinimumSize(QtCore.QSize(601, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.Choose_toolButton = QtGui.QToolButton(self.groupBox_2)
        self.Choose_toolButton.setGeometry(QtCore.QRect(20, 30, 71, 19))
        self.Choose_toolButton.setMinimumSize(QtCore.QSize(71, 0))
        self.Choose_toolButton.setMaximumSize(QtCore.QSize(16777215, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Choose_toolButton.setFont(font)
        self.Choose_toolButton.setObjectName(_fromUtf8("Choose_toolButton"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 500, 201, 181))
        self.frame_3.setMinimumSize(QtCore.QSize(201, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 181))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.frame_3)
        self.groupBox_5.setEnabled(False)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 20, 171, 151))
        self.groupBox_5.setMinimumSize(QtCore.QSize(171, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 151))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.Sstop_pushButton = QtGui.QPushButton(self.groupBox_5)
        self.Sstop_pushButton.setGeometry(QtCore.QRect(90, 20, 75, 23))
        self.Sstop_pushButton.setMinimumSize(QtCore.QSize(75, 0))
        self.Sstop_pushButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.Sstop_pushButton.setObjectName(_fromUtf8("Sstop_pushButton"))
        self.Sstart_pushButton = QtGui.QPushButton(self.groupBox_5)
        self.Sstart_pushButton.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.Sstart_pushButton.setMinimumSize(QtCore.QSize(75, 0))
        self.Sstart_pushButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.Sstart_pushButton.setObjectName(_fromUtf8("Sstart_pushButton"))
        self.line_5 = QtGui.QFrame(self.groupBox_5)
        self.line_5.setGeometry(QtCore.QRect(0, 50, 171, 20))
        self.line_5.setMinimumSize(QtCore.QSize(171, 0))
        self.line_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 80, 151, 61))
        self.groupBox_7.setMinimumSize(QtCore.QSize(151, 0))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 61))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.spinBox = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox.setGeometry(QtCore.QRect(30, 20, 71, 22))
        self.spinBox.setMinimumSize(QtCore.QSize(71, 0))
        self.spinBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 90, 191, 81))
        self.frame_4.setMinimumSize(QtCore.QSize(191, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 101))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.groupBox_6 = QtGui.QGroupBox(self.frame_4)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 0, 161, 71))
        self.groupBox_6.setMinimumSize(QtCore.QSize(161, 0))
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.comboBox = QtGui.QComboBox(self.groupBox_6)
        self.comboBox.setGeometry(QtCore.QRect(20, 30, 111, 22))
        self.comboBox.setMinimumSize(QtCore.QSize(111, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 180, 191, 81))
        self.frame.setMinimumSize(QtCore.QSize(191, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 81))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.groupBox_3 = QtGui.QGroupBox(self.frame)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.groupBox_3.setMinimumSize(QtCore.QSize(161, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.Tstart_pushButton = QtGui.QPushButton(self.groupBox_3)
        self.Tstart_pushButton.setGeometry(QtCore.QRect(10, 30, 71, 23))
        self.Tstart_pushButton.setMinimumSize(QtCore.QSize(71, 0))
        self.Tstart_pushButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.Tstart_pushButton.setObjectName(_fromUtf8("Tstart_pushButton"))
        self.Tstop_pushButton = QtGui.QPushButton(self.groupBox_3)
        self.Tstop_pushButton.setGeometry(QtCore.QRect(90, 30, 71, 23))
        self.Tstop_pushButton.setMinimumSize(QtCore.QSize(71, 0))
        self.Tstop_pushButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.Tstop_pushButton.setObjectName(_fromUtf8("Tstop_pushButton"))
        self.groupBox_9 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(0, 780, 1271, 61))
        self.groupBox_9.setMinimumSize(QtCore.QSize(731, 0))
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setMinimumSize(QtCore.QSize(2, 0))
        self.layoutWidget.setMaximumSize(QtCore.QSize(16777215, 2))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setMinimumSize(QtCore.QSize(2, 0))
        self.layoutWidget1.setMaximumSize(QtCore.QSize(16777215, 2))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setEnabled(False)
        self.frame_2.setGeometry(QtCore.QRect(10, 280, 191, 191))
        self.frame_2.setMinimumSize(QtCore.QSize(191, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 191))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.frame_2)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 171, 161))
        self.groupBox_4.setMinimumSize(QtCore.QSize(171, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 161))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.Cstart_pushButton = QtGui.QPushButton(self.groupBox_4)
        self.Cstart_pushButton.setEnabled(False)
        self.Cstart_pushButton.setGeometry(QtCore.QRect(10, 20, 61, 23))
        self.Cstart_pushButton.setMinimumSize(QtCore.QSize(61, 0))
        self.Cstart_pushButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.Cstart_pushButton.setObjectName(_fromUtf8("Cstart_pushButton"))
        self.Cstop_pushButton = QtGui.QPushButton(self.groupBox_4)
        self.Cstop_pushButton.setEnabled(False)
        self.Cstop_pushButton.setGeometry(QtCore.QRect(80, 20, 71, 23))
        self.Cstop_pushButton.setMinimumSize(QtCore.QSize(61, 0))
        self.Cstop_pushButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.Cstop_pushButton.setObjectName(_fromUtf8("Cstop_pushButton"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_8.setEnabled(False)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 60, 120, 80))
        self.groupBox_8.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(12, 19, 101, 51))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 170, 221, 16))
        self.line_4.setMinimumSize(QtCore.QSize(221, 0))
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(0, 270, 221, 16))
        self.line_6.setMinimumSize(QtCore.QSize(221, 0))
        self.line_6.setMaximumSize(QtCore.QSize(16777215, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(0, 480, 221, 16))
        self.line_7.setMinimumSize(QtCore.QSize(221, 0))
        self.line_7.setMaximumSize(QtCore.QSize(16777215, 16))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1315, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionYAST_Help = QtGui.QAction(MainWindow)
        self.actionYAST_Help.setObjectName(_fromUtf8("actionYAST_Help"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionYAST_Help)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "YAST", None))
        self.groupBox.setTitle(_translate("MainWindow", "Output", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Filter", None))
        self.Choose_toolButton.setText(
            _translate("MainWindow", "Choose", None))
        self.groupBox_5.setTitle(_translate(
            "MainWindow", "Sessionization", None))
        self.Sstop_pushButton.setText(_translate("MainWindow", "Stop", None))
        self.Sstart_pushButton.setText(_translate("MainWindow", "Start", None))
        self.groupBox_7.setTitle(_translate(
            "MainWindow", "Enter Session Time", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Log Format", None))
        self.comboBox.setItemText(0, _translate(
            "MainWindow", "Proxy Log File", None))
        self.comboBox.setItemText(1, _translate(
            "MainWindow", "Web Log File", None))
        self.comboBox.setItemText(2, _translate(
            "MainWindow", "Squid Log File", None))
        self.groupBox_3.setTitle(_translate(
            "MainWindow", "Tokenization", None))
        self.Tstart_pushButton.setText(_translate("MainWindow", "Start", None))
        self.Tstop_pushButton.setText(_translate("MainWindow", "Stop", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Status", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Clean", None))
        self.Cstart_pushButton.setText(_translate("MainWindow", "Start", None))
        self.Cstop_pushButton.setText(_translate("MainWindow", "Stop", None))
        self.groupBox_8.setTitle(_translate(
            "MainWindow", "To be Exclude", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_As.setText(_translate(
            "MainWindow", "Save As...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionYAST_Help.setText(
            _translate("MainWindow", "YAST Help", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
